// <auto-generated />
namespace CampanasDelDesierto_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class relationShip_PagoPorProducto_RecpecionProducto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relationShip_PagoPorProducto_RecpecionProducto));
        
        string IMigrationMetadata.Id
        {
            get { return "201705211939490_relationShip_PagoPorProducto_RecpecionProducto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
