// <auto-generated />
namespace CampanasDelDesierto_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedField_VariedadesOrganicas4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedField_VariedadesOrganicas4));
        
        string IMigrationMetadata.Id
        {
            get { return "201707202120360_addedField_VariedadesOrganicas4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
