// <auto-generated />
namespace CampanasDelDesierto_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nuevaEntidad_EmisionDeCheques : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nuevaEntidad_EmisionDeCheques));
        
        string IMigrationMetadata.Id
        {
            get { return "201704282158141_nuevaEntidad_EmisionDeCheques"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
