// <auto-generated />
namespace CampanasDelDesierto_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class monto_pago_abono_preciosion4digitos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(monto_pago_abono_preciosion4digitos));
        
        string IMigrationMetadata.Id
        {
            get { return "201707110322052_monto_pago_abono_preciosion4digitos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
