// <auto-generated />
namespace CampanasDelDesierto_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fecha_semana_RecepcionDeProducto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fecha_semana_RecepcionDeProducto));
        
        string IMigrationMetadata.Id
        {
            get { return "201705140204278_fecha_semana_RecepcionDeProducto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
