// <auto-generated />
namespace CampanasDelDesierto_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class precision_precioDolar_PrestamoYAbonoCapital : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(precision_precioDolar_PrestamoYAbonoCapital));
        
        string IMigrationMetadata.Id
        {
            get { return "201704250356289_precision_precioDolar_PrestamoYAbonoCapital"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
