// <auto-generated />
namespace CampanasDelDesierto_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class requiered_Fecha_NumRecibo_Recepciones : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requiered_Fecha_NumRecibo_Recepciones));
        
        string IMigrationMetadata.Id
        {
            get { return "201705290223236_requiered_Fecha_NumRecibo_Recepciones"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
