// <auto-generated />
namespace CampanasDelDesierto_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class concepto_A_TipoDeMovimiento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(concepto_A_TipoDeMovimiento));
        
        string IMigrationMetadata.Id
        {
            get { return "201705312110260_concepto_A_TipoDeMovimiento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
