// <auto-generated />
namespace CampanasDelDesierto_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class pagos_prestamos_addedField_isINteres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pagos_prestamos_addedField_isINteres));
        
        string IMigrationMetadata.Id
        {
            get { return "201707100155224_pagos_prestamos_addedField_isINteres"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
