// <auto-generated />
namespace CampanasDelDesierto_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nuevatabla_retencionesDeCheques : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nuevatabla_retencionesDeCheques));
        
        string IMigrationMetadata.Id
        {
            get { return "201709132017415_nuevatabla_retencionesDeCheques"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
