// <auto-generated />
namespace CampanasDelDesierto_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Nueva_Tabla_AdquisicionDeActivo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nueva_Tabla_AdquisicionDeActivo));
        
        string IMigrationMetadata.Id
        {
            get { return "201709271743271_Nueva_Tabla_AdquisicionDeActivo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
