// <auto-generated />
namespace CampanasDelDesierto_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedFields_Retenciones_LiquidacionSemanal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedFields_Retenciones_LiquidacionSemanal));
        
        string IMigrationMetadata.Id
        {
            get { return "201706090253414_addedFields_Retenciones_LiquidacionSemanal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
