// <auto-generated />
namespace CampanasDelDesierto_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class prestamo_abono_par_relacion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(prestamo_abono_par_relacion));
        
        string IMigrationMetadata.Id
        {
            get { return "201707050728457_prestamo_abono_par_relacion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
