// <auto-generated />
namespace CampanasDelDesierto_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedFiedl_liquidacionSemanal_timePeriod_precioDelDolar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedFiedl_liquidacionSemanal_timePeriod_precioDelDolar));
        
        string IMigrationMetadata.Id
        {
            get { return "201706081936301_addedFiedl_liquidacionSemanal_timePeriod_precioDelDolar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
