// <auto-generated />
namespace CampanasDelDesierto_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class liquidacionID_Requiered_Retencion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(liquidacionID_Requiered_Retencion));
        
        string IMigrationMetadata.Id
        {
            get { return "201706100340411_liquidacionID_Requiered_Retencion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
