// <auto-generated />
namespace CampanasDelDesierto_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_field_VariedadOrganica1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_field_VariedadOrganica1));
        
        string IMigrationMetadata.Id
        {
            get { return "201707171838551_added_field_VariedadOrganica1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
